
name: mirror test2
on:
  push:
    branches:
      - main

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          docker run quay.io/skopeo/stable:v1.2.0 sync \
            --src-no-creds \
            --dest-creds ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} \
            --src docker \
            --dest docker \
            k8s.gcr.io/kube-controller-manager docker.io/k8smx           
