
name: mirror test
on:
  push:
    branches:
      - main
  schedule:
  - cron: "* * * * *"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          cat <<EOF >xxx
          k8s.gcr.io/kube-apiserver k8smx/kube-apiserver v1.20.5
          EOF
          docker run \
            -v `pwd`/xxx:/xxx \
            -e SRC_REGISTRY=k8s.gcr.io \
            -e DST_USERNAME=${{ secrets.DOCKER_USERNAME }} \
            -e DST_USERNAME=${{ secrets.DOCKER_PASSWORD }} \
            wuhuizuo/dockerx-mirror-k8s:edge /xxx
            
